### ISSUE TITLE
Zmk won't build

### ISSUE THREAD

**Issue by pnhearer** [jporter-dev/keymaps#4]
Couldn't get the zmk to build. on a Crkbd 5 row with Nice!Nanov2 + NiceView. Tried copying just the keymap over and it would not build at all. tried to piece the thing together bit by bit, no luck either. Not sure what the issue is.

**Comment by jporter-dev** [comment]
Hey - sorry, I haven't been keeping my keymap up to date with ZMK as I haven't had to modify it in a while. I'll take a look and see what breaking changes have happened.

**Comment by jporter-dev** [comment]
[Here](https://github.com/jporter-dev/zmk-config) is the latest version of the firmware.
